# Generated by Django 6.0.8 on 2026-08-09 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("STAT", "Statistic"),
                            ("CHART", "Chart"),
                            ("TABLE", "Table"),
                            ("CALENDAR", "Calendar"),
                            ("ACTIVITY", "Activity"),
                            ("ALERT", "Alert"),
                            ("LIST", "List"),
                        ],
                        max_length=20,
                    ),
                ),
                ("component_key", models.CharField(max_length=150)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("position_x", models.PositiveSmallIntegerField(default=0)),
                ("position_y", models.PositiveSmallIntegerField(default=0)),
                ("width", models.PositiveSmallIntegerField(default=4)),
                ("height", models.PositiveSmallIntegerField(default=3)),
                ("is_visible", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "dashboard_widgets",
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="UserDashboardPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("layout_configuration", models.JSONField(blank=True, default=dict)),
                ("compact_mode", models.BooleanField(default=False)),
                ("auto_refresh_enabled", models.BooleanField(default=True)),
                ("refresh_interval_seconds", models.PositiveIntegerField(default=60)),
            ],
            options={
                "db_table": "user_dashboard_preferences",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("YEARLY", "Yearly"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True)),
                ("metrics", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analytics_snapshots",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator Dashboard"),
                            ("DOCTOR", "Doctor Dashboard"),
                            ("PATIENT", "Patient Dashboard"),
                            ("NURSE", "Nurse Dashboard"),
                            ("RADIOLOGIST", "Radiologist Dashboard"),
                            ("LAB_TECHNICIAN", "Lab Technician Dashboard"),
                            ("STAFF", "Staff Dashboard"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboards",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "dashboards",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DashboardFilter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("filters", models.JSONField(default=dict)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to="dashboard.dashboard",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_filters",
            },
        ),
    ]
