# Generated by Django 6.0.8 on 2026-08-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardfilter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_filters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dashboardwidget",
            name="dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widgets",
                to="dashboard.dashboard",
            ),
        ),
        migrations.AddField(
            model_name="userdashboardpreference",
            name="default_dashboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users_using_as_default",
                to="dashboard.dashboard",
            ),
        ),
        migrations.AddField(
            model_name="userdashboardpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_preference",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="analyticssnapshot",
            index=models.Index(
                fields=["organization", "snapshot_type", "snapshot_date"],
                name="analytics_snapshot_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="analyticssnapshot",
            constraint=models.UniqueConstraint(
                fields=("organization", "snapshot_type", "snapshot_date"),
                name="unique_analytics_snapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["dashboard_type", "is_default"],
                name="dashboard_type_default_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_dashboard_name_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardfilter",
            index=models.Index(
                fields=["user", "dashboard", "is_default"],
                name="dashboard_filter_default_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardfilter",
            constraint=models.UniqueConstraint(
                fields=("user", "dashboard", "name"),
                name="unique_user_dashboard_filter",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardwidget",
            index=models.Index(
                fields=["dashboard", "is_visible"], name="widget_dashboard_visible_idx"
            ),
        ),
    ]
