# Generated by Django 6.0.8 on 2026-08-09 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIHumanReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUIRED", "Not Required"),
                            ("PENDING", "Pending"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("MODIFIED", "Modified"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewer_comments", models.TextField(blank=True)),
                ("corrected_findings", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ai_human_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIInferenceJob",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_reference",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("input_storage_key", models.CharField(blank=True, max_length=1024)),
                ("input_checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("output_storage_key", models.CharField(blank=True, max_length=1024)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_time_ms",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("worker_id", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "ai_inference_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("CLASSIFICATION", "Classification"),
                            ("DETECTION", "Detection"),
                            ("SEGMENTATION", "Segmentation"),
                            ("PREDICTION", "Prediction"),
                            ("NLP", "Natural Language Processing"),
                            ("MULTIMODAL", "Multimodal"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("PYTORCH", "PyTorch"),
                            ("TENSORFLOW", "TensorFlow"),
                            ("SKLEARN", "Scikit-learn"),
                            ("ONNX", "ONNX"),
                            ("HUGGINGFACE", "Hugging Face"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DEVELOPMENT", "Development"),
                            ("VALIDATION", "Validation"),
                            ("PRODUCTION", "Production"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="DEVELOPMENT",
                        max_length=20,
                    ),
                ),
                ("repository_url", models.URLField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                ("license_name", models.CharField(blank=True, max_length=255)),
                (
                    "is_clinical_use_approved",
                    models.BooleanField(db_index=True, default=False),
                ),
            ],
            options={
                "db_table": "ai_models",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIModelVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=100)),
                ("artifact_storage_key", models.CharField(max_length=1024)),
                ("artifact_sha256", models.CharField(max_length=64)),
                (
                    "configuration_storage_key",
                    models.CharField(blank=True, max_length=1024),
                ),
                ("release_notes", models.TextField(blank=True)),
                (
                    "input_schema_version",
                    models.CharField(default="1.0", max_length=50),
                ),
                (
                    "output_schema_version",
                    models.CharField(default="1.0", max_length=50),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=7, null=True
                    ),
                ),
                (
                    "sensitivity",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=7, null=True
                    ),
                ),
                (
                    "specificity",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=7, null=True
                    ),
                ),
                (
                    "auc",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=7, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ai_model_versions",
                "ordering": ["model", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("CLASSIFICATION", "Classification"),
                            ("DETECTION", "Detection"),
                            ("SEGMENTATION", "Segmentation"),
                            ("RISK", "Risk Score"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(db_index=True, max_length=255)),
                ("probability", models.DecimalField(decimal_places=6, max_digits=7)),
                ("severity", models.CharField(blank=True, max_length=50)),
                ("anatomical_location", models.CharField(blank=True, max_length=255)),
                ("coordinates", models.JSONField(blank=True, default=dict)),
                ("mask_storage_key", models.CharField(blank=True, max_length=1024)),
                ("explanation", models.TextField(blank=True)),
            ],
            options={
                "db_table": "ai_predictions",
                "ordering": ["-probability"],
            },
        ),
    ]
