# Generated by Django 6.0.8 on 2026-08-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_pipeline", "0001_initial"),
        ("imaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aihumanreview",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiinferencejob",
            name="imaging_study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_inference_jobs",
                to="imaging.imagingstudy",
            ),
        ),
        migrations.AddField(
            model_name="aiinferencejob",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_jobs_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aihumanreview",
            name="job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="human_review",
                to="ai_pipeline.aiinferencejob",
            ),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_models_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aimodelversion",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="ai_pipeline.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="aiinferencejob",
            name="model_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inference_jobs",
                to="ai_pipeline.aimodelversion",
            ),
        ),
        migrations.AddField(
            model_name="prediction",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="predictions",
                to="ai_pipeline.aiinferencejob",
            ),
        ),
        migrations.AddIndex(
            model_name="aihumanreview",
            index=models.Index(
                fields=["status", "created_at"], name="ai_review_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(
                fields=["model_type", "status"], name="ai_model_type_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(
                fields=["is_clinical_use_approved", "status"],
                name="ai_model_clinical_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aimodelversion",
            index=models.Index(
                fields=["model", "is_active"], name="ai_version_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="aimodelversion",
            constraint=models.UniqueConstraint(
                fields=("model", "version"), name="unique_ai_model_version"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinferencejob",
            index=models.Index(
                fields=["status", "priority"], name="ai_job_status_priority_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinferencejob",
            index=models.Index(
                fields=["model_version", "created_at"], name="ai_job_model_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinferencejob",
            index=models.Index(
                fields=["imaging_study", "status"], name="ai_job_study_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prediction",
            index=models.Index(
                fields=["job", "label"], name="prediction_job_label_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prediction",
            index=models.Index(
                fields=["label", "probability"], name="prediction_label_prob_idx"
            ),
        ),
    ]
