# Generated by Django 6.0.8 on 2026-08-09 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("allergen", models.CharField(db_index=True, max_length=255)),
                ("reaction", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MILD", "Mild"),
                            ("MODERATE", "Moderate"),
                            ("SEVERE", "Severe"),
                            ("LIFE_THREATENING", "Life Threatening"),
                        ],
                        default="MILD",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RESOLVED", "Resolved")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "allergies",
            },
        ),
        migrations.CreateModel(
            name="ClinicalEncounter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("OUTPATIENT", "Outpatient"),
                            ("INPATIENT", "Inpatient"),
                            ("EMERGENCY", "Emergency"),
                            ("TELEMEDICINE", "Telemedicine"),
                            ("FOLLOW_UP", "Follow-up"),
                        ],
                        db_index=True,
                        default="OUTPATIENT",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("chief_complaint", models.TextField(blank=True)),
                ("history_of_present_illness", models.TextField(blank=True)),
                ("clinical_summary", models.TextField(blank=True)),
                ("examination_notes", models.TextField(blank=True)),
                ("treatment_plan", models.TextField(blank=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "clinical_encounters",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("PROGRESS", "Progress Note"),
                            ("CONSULTATION", "Consultation Note"),
                            ("DISCHARGE", "Discharge Note"),
                            ("NURSING", "Nursing Note"),
                            ("OTHER", "Other"),
                        ],
                        default="PROGRESS",
                        max_length=30,
                    ),
                ),
                ("content", models.TextField()),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("is_signed", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "db_table": "clinical_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=30)),
                ("description", models.CharField(max_length=500)),
                (
                    "diagnosis_type",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary"),
                            ("SECONDARY", "Secondary"),
                            ("DIFFERENTIAL", "Differential"),
                            ("HISTORICAL", "Historical"),
                        ],
                        default="PRIMARY",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RESOLVED", "Resolved"),
                            ("INACTIVE", "Inactive"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("clinical_notes", models.TextField(blank=True)),
                ("diagnosed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "diagnoses",
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record_number",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
            ],
            options={
                "db_table": "medical_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("medication_name", models.CharField(db_index=True, max_length=255)),
                ("generic_name", models.CharField(blank=True, max_length=255)),
                ("dosage", models.CharField(max_length=100)),
                ("route", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("instructions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("DISCONTINUED", "Discontinued"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("prescribed_at", models.DateTimeField()),
                ("discontinued_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "medications",
                "ordering": ["-prescribed_at"],
            },
        ),
        migrations.CreateModel(
            name="VitalSign",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "temperature_celsius",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "heart_rate_bpm",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "respiratory_rate_bpm",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "systolic_bp_mmhg",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "diastolic_bp_mmhg",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "oxygen_saturation_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("recorded_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "vital_signs",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
