# Generated by Django 6.0.8 on 2026-08-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_initial"),
        ("emr", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="allergy",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allergies_recorded",
                to="users.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="clinicalencounter",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clinical_encounter",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="clinicalencounter",
            name="attending_doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clinical_encounters",
                to="users.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="clinicalencounter",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clinical_encounters",
                to="users.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="clinicalnote",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clinical_notes_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clinicalnote",
            name="encounter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clinical_notes",
                to="emr.clinicalencounter",
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="diagnosed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diagnoses_created",
                to="users.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="encounter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diagnoses",
                to="emr.clinicalencounter",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medical_record",
                to="users.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="primary_physician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_medical_records",
                to="users.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="clinicalencounter",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="encounters",
                to="emr.medicalrecord",
            ),
        ),
        migrations.AddField(
            model_name="allergy",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allergies",
                to="emr.medicalrecord",
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="encounter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medications",
                to="emr.clinicalencounter",
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medications",
                to="emr.medicalrecord",
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="prescribed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medications_prescribed",
                to="users.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="encounter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vital_signs",
                to="emr.clinicalencounter",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vital_signs_recorded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalnote",
            index=models.Index(
                fields=["encounter", "note_type"], name="clinical_note_enc_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalnote",
            index=models.Index(
                fields=["author", "created_at"], name="clinical_note_author_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosis",
            index=models.Index(
                fields=["encounter", "diagnosis_type"], name="diagnosis_enc_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosis",
            index=models.Index(
                fields=["code", "status"], name="diagnosis_code_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["status", "is_active"], name="emr_status_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalencounter",
            index=models.Index(
                fields=["patient", "started_at"], name="encounter_patient_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalencounter",
            index=models.Index(
                fields=["attending_doctor", "started_at"],
                name="encounter_doctor_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalencounter",
            index=models.Index(
                fields=["status", "started_at"], name="encounter_status_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allergy",
            index=models.Index(
                fields=["medical_record", "status"], name="allergy_record_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medication",
            index=models.Index(
                fields=["medical_record", "status"], name="medication_record_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medication",
            index=models.Index(
                fields=["medication_name", "status"], name="medication_name_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vitalsign",
            index=models.Index(
                fields=["encounter", "recorded_at"], name="vitals_encounter_date_idx"
            ),
        ),
    ]
