# Generated by Django 6.0.8 on 2026-08-09 11:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("HOME", "Home"),
                            ("WORK", "Work"),
                            ("ORGANIZATION", "Organization"),
                            ("OTHER", "Other"),
                        ],
                        default="HOME",
                        max_length=20,
                    ),
                ),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "db_table": "addresses",
                "indexes": [
                    models.Index(
                        fields=["city", "state"], name="address_city_state_idx"
                    ),
                    models.Index(
                        fields=["postal_code"], name="address_postal_code_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "Hospital"),
                            ("CLINIC", "Clinic"),
                            ("DIAGNOSTIC_CENTER", "Diagnostic Center"),
                            ("IMAGING_CENTER", "Imaging Center"),
                            ("LABORATORY", "Laboratory"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="CLINIC",
                        max_length=30,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "organizations",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["organization_type", "is_active"],
                        name="org_type_active_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("full_name", models.CharField(max_length=150)),
                ("relationship", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("alternate_phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_contacts",
                        to="core.address",
                    ),
                ),
            ],
            options={
                "db_table": "emergency_contacts",
                "indexes": [
                    models.Index(fields=["phone_number"], name="emergency_phone_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "code",
                    models.CharField(
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "departments",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"], name="dept_org_active_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "name"),
                        name="unique_department_name_per_org",
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "code"),
                        name="unique_department_code_per_org",
                    ),
                ],
            },
        ),
    ]
