# Generated by Django 6.0.8 on 2026-08-09 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagingAIProcessing",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("model_version", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("result_storage_key", models.CharField(blank=True, max_length=1024)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=6, null=True
                    ),
                ),
            ],
            options={
                "db_table": "imaging_ai_processing",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImagingSeries",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "series_instance_uid",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("series_number", models.PositiveIntegerField()),
                ("series_description", models.CharField(blank=True, max_length=500)),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("XR", "X-Ray"),
                            ("CT", "Computed Tomography"),
                            ("MR", "Magnetic Resonance Imaging"),
                            ("US", "Ultrasound"),
                            ("PT", "Positron Emission Tomography"),
                            ("MG", "Mammography"),
                            ("RF", "Fluoroscopy"),
                            ("DX", "Bone Densitometry"),
                            ("OT", "Other"),
                        ],
                        max_length=5,
                    ),
                ),
                ("body_part", models.CharField(blank=True, max_length=100)),
                ("number_of_instances", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "imaging_series",
                "ordering": ["series_number"],
            },
        ),
        migrations.CreateModel(
            name="RadiologyReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PRELIMINARY", "Preliminary"),
                            ("FINAL", "Final"),
                            ("AMENDED", "Amended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("clinical_history", models.TextField(blank=True)),
                ("findings", models.TextField(blank=True)),
                ("impression", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("report_text", models.TextField(blank=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "radiology_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DICOMInstance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sop_instance_uid",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("instance_number", models.PositiveIntegerField()),
                ("storage_key", models.CharField(max_length=1024, unique=True)),
                ("file_size_bytes", models.PositiveBigIntegerField(default=0)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("transfer_syntax_uid", models.CharField(blank=True, max_length=128)),
                ("sop_class_uid", models.CharField(blank=True, max_length=128)),
                ("rows", models.PositiveIntegerField(blank=True, null=True)),
                ("columns", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "bits_allocated",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "bits_stored",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "pixel_representation",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="imaging.imagingseries",
                    ),
                ),
            ],
            options={
                "db_table": "dicom_instances",
            },
        ),
        migrations.CreateModel(
            name="ImagingStudy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "study_instance_uid",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "accession_number",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("XR", "X-Ray"),
                            ("CT", "Computed Tomography"),
                            ("MR", "Magnetic Resonance Imaging"),
                            ("US", "Ultrasound"),
                            ("PT", "Positron Emission Tomography"),
                            ("MG", "Mammography"),
                            ("RF", "Fluoroscopy"),
                            ("DX", "Bone Densitometry"),
                            ("OT", "Other"),
                        ],
                        db_index=True,
                        max_length=5,
                    ),
                ),
                ("body_part", models.CharField(max_length=100)),
                ("study_description", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ORDERED", "Ordered"),
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="ORDERED",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "Stat"),
                        ],
                        db_index=True,
                        default="ROUTINE",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("performed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("clinical_indication", models.TextField(blank=True)),
                ("clinical_history", models.TextField(blank=True)),
                ("referring_physician_notes", models.TextField(blank=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imaging_studies",
                        to="emr.clinicalencounter",
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imaging_studies",
                        to="emr.medicalrecord",
                    ),
                ),
            ],
            options={
                "db_table": "imaging_studies",
                "ordering": ["-requested_at"],
            },
        ),
    ]
