# Generated by Django 6.0.8 on 2026-08-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("imaging", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagingstudy",
            name="ordered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="imaging_studies_ordered",
                to="users.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="imaging_studies",
                to="users.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="imagingseries",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="series",
                to="imaging.imagingstudy",
            ),
        ),
        migrations.AddField(
            model_name="imagingaiprocessing",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ai_processing_jobs",
                to="imaging.imagingstudy",
            ),
        ),
        migrations.AddField(
            model_name="radiologyreport",
            name="radiologist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="radiology_reports",
                to="users.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="radiologyreport",
            name="study",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="radiology_report",
                to="imaging.imagingstudy",
            ),
        ),
        migrations.AddIndex(
            model_name="dicominstance",
            index=models.Index(
                fields=["series", "instance_number"], name="dicom_series_instance_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dicominstance",
            constraint=models.UniqueConstraint(
                fields=("series", "instance_number"), name="unique_instance_per_series"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingstudy",
            index=models.Index(
                fields=["patient", "requested_at"], name="imaging_patient_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingstudy",
            index=models.Index(
                fields=["modality", "status"], name="imaging_modality_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingstudy",
            index=models.Index(
                fields=["status", "priority"], name="imaging_status_priority_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingseries",
            index=models.Index(
                fields=["study", "series_number"], name="series_study_number_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="imagingseries",
            constraint=models.UniqueConstraint(
                fields=("study", "series_number"), name="unique_series_number_per_study"
            ),
        ),
        migrations.AddIndex(
            model_name="imagingaiprocessing",
            index=models.Index(fields=["study", "status"], name="ai_study_status_idx"),
        ),
        migrations.AddIndex(
            model_name="imagingaiprocessing",
            index=models.Index(
                fields=["model_name", "model_version"], name="ai_model_version_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="radiologyreport",
            index=models.Index(
                fields=["radiologist", "status"], name="report_radiologist_status_idx"
            ),
        ),
    ]
