# Generated by Django 6.0.8 on 2026-08-09 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("READ", "Read"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("EXPORT", "Export"),
                            ("DOWNLOAD", "Download"),
                            ("UPLOAD", "Upload"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("AI_INFERENCE", "AI Inference"),
                            ("AI_REVIEW", "AI Review"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("PERMISSION_CHANGE", "Permission Change"),
                            ("SECURITY_EVENT", "Security Event"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AUTHENTICATION", "Authentication"),
                            ("AUTHORIZATION", "Authorization"),
                            ("PATIENT_DATA", "Patient Data"),
                            ("CLINICAL", "Clinical"),
                            ("IMAGING", "Imaging"),
                            ("AI", "Artificial Intelligence"),
                            ("BILLING", "Billing"),
                            ("ADMINISTRATION", "Administration"),
                            ("SECURITY", "Security"),
                            ("SYSTEM", "System"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("target_model", models.CharField(blank=True, max_length=255)),
                ("target_object_id", models.CharField(blank=True, max_length=255)),
                ("target_display", models.CharField(blank=True, max_length=500)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("endpoint", models.CharField(blank=True, max_length=500)),
                ("http_method", models.CharField(blank=True, max_length=10)),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "audit_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuthenticationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_attempted", models.EmailField(blank=True, max_length=254)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILURE", "Login Failure"),
                            ("LOGOUT", "Logout"),
                            ("TOKEN_REFRESH", "Token Refresh"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PASSWORD_RESET_REQUEST", "Password Reset Request"),
                            ("PASSWORD_RESET_SUCCESS", "Password Reset Success"),
                            ("ACCOUNT_LOCKED", "Account Locked"),
                            ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("success", models.BooleanField(db_index=True, default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "authentication_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientDataAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("EXPORT", "Export"),
                            ("DOWNLOAD", "Download"),
                            ("PRINT", "Print"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("resource_type", models.CharField(max_length=255)),
                ("resource_id", models.CharField(max_length=255)),
                ("purpose", models.CharField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "patient_data_access_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SUSPICIOUS_LOGIN", "Suspicious Login"),
                            ("RATE_LIMIT", "Rate Limit Triggered"),
                            ("INVALID_TOKEN", "Invalid Token"),
                            ("PERMISSION_DENIED", "Permission Denied"),
                            ("UNAUTHORIZED_ACCESS", "Unauthorized Access"),
                            ("DATA_EXPORT", "Data Export"),
                            ("FILE_ACCESS", "File Access"),
                            ("MALICIOUS_REQUEST", "Malicious Request"),
                            ("SYSTEM_ALERT", "System Alert"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("endpoint", models.CharField(blank=True, max_length=500)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "security_events",
                "ordering": ["-created_at"],
            },
        ),
    ]
