# Generated by Django 6.0.8 on 2026-08-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authenticationevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authentication_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientdataaccesslog",
            name="accessed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient_data_access_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientdataaccesslog",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="data_access_logs",
                to="users.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="security_events_resolved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="security_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["actor", "created_at"], name="audit_actor_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["category", "created_at"], name="audit_category_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="audit_event_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["severity", "created_at"], name="audit_severity_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["target_model", "target_object_id"], name="audit_target_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["ip_address", "created_at"], name="audit_ip_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationevent",
            index=models.Index(
                fields=["user", "created_at"], name="auth_event_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationevent",
            index=models.Index(
                fields=["email_attempted", "created_at"],
                name="auth_event_email_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationevent",
            index=models.Index(
                fields=["ip_address", "created_at"], name="auth_event_ip_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdataaccesslog",
            index=models.Index(
                fields=["patient", "created_at"], name="patient_access_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdataaccesslog",
            index=models.Index(
                fields=["accessed_by", "created_at"], name="accessor_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientdataaccesslog",
            index=models.Index(
                fields=["resource_type", "resource_id"], name="patient_resource_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["severity", "resolved", "created_at"],
                name="security_open_events_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["event_type", "created_at"], name="security_type_date_idx"
            ),
        ),
    ]
