# Generated by Django 6.0.8 on 2026-08-09 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicalReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_number",
                    models.CharField(
                        db_index=True, editable=False, max_length=50, unique=True
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("CLINICAL", "Clinical Report"),
                            ("DISCHARGE", "Discharge Report"),
                            ("CONSULTATION", "Consultation Report"),
                            ("LABORATORY", "Laboratory Report"),
                            ("RADIOLOGY", "Radiology Report"),
                            ("PATHOLOGY", "Pathology Report"),
                            ("AI_ANALYSIS", "AI Analysis Report"),
                            ("MEDICAL_SUMMARY", "Medical Summary"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("FINAL", "Final"),
                            ("AMENDED", "Amended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("findings", models.TextField(blank=True)),
                ("impression", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "clinical_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("HTML", "HTML"),
                            ("PDF", "PDF"),
                            ("DOCX", "DOCX"),
                            ("JSON", "JSON"),
                        ],
                        max_length=10,
                    ),
                ),
                ("storage_key", models.CharField(max_length=1024, unique=True)),
                ("file_name", models.CharField(max_length=500)),
                ("content_type", models.CharField(max_length=150)),
                ("file_size_bytes", models.PositiveBigIntegerField(default=0)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "generated_reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportExport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("HTML", "HTML"),
                            ("PDF", "PDF"),
                            ("DOCX", "DOCX"),
                            ("JSON", "JSON"),
                        ],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("storage_key", models.CharField(blank=True, max_length=1024)),
                ("failure_reason", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "report_exports",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("CLINICAL", "Clinical Report"),
                            ("DISCHARGE", "Discharge Report"),
                            ("CONSULTATION", "Consultation Report"),
                            ("LABORATORY", "Laboratory Report"),
                            ("RADIOLOGY", "Radiology Report"),
                            ("PATHOLOGY", "Pathology Report"),
                            ("AI_ANALYSIS", "AI Analysis Report"),
                            ("MEDICAL_SUMMARY", "Medical Summary"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("template_content", models.TextField()),
                ("schema", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "report_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportVersion",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("findings", models.TextField(blank=True)),
                ("impression", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("change_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "report_versions",
                "ordering": ["report", "-version_number"],
            },
        ),
    ]
