# Generated by Django 6.0.8 on 2026-08-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emr", "0002_initial"),
        ("imaging", "0002_initial"),
        ("reports", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalreport",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clinicalreport",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="emr.clinicalencounter",
            ),
        ),
        migrations.AddField(
            model_name="clinicalreport",
            name="imaging_study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_reports",
                to="imaging.imagingstudy",
            ),
        ),
        migrations.AddField(
            model_name="clinicalreport",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clinical_reports",
                to="emr.medicalrecord",
            ),
        ),
        migrations.AddField(
            model_name="clinicalreport",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clinical_reports",
                to="users.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="clinicalreport",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clinicalreport",
            name="signed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports_signed",
                to="users.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="generated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_artifacts",
                to="reports.clinicalreport",
            ),
        ),
        migrations.AddField(
            model_name="reportexport",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exports",
                to="reports.clinicalreport",
            ),
        ),
        migrations.AddField(
            model_name="reportexport",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="report_exports_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="report_templates_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clinicalreport",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="reports.reporttemplate",
            ),
        ),
        migrations.AddField(
            model_name="reportversion",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="report_versions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportversion",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="reports.clinicalreport",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["report", "format"], name="generated_report_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexport",
            index=models.Index(
                fields=["status", "requested_at"], name="report_export_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportexport",
            index=models.Index(
                fields=["requested_by", "requested_at"], name="report_export_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["report_type", "is_active"], name="report_template_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalreport",
            index=models.Index(
                fields=["patient", "created_at"], name="report_patient_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalreport",
            index=models.Index(
                fields=["medical_record", "report_type"], name="report_record_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalreport",
            index=models.Index(
                fields=["status", "report_type"], name="report_status_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalreport",
            index=models.Index(
                fields=["author", "created_at"], name="report_author_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportversion",
            index=models.Index(
                fields=["report", "version_number"], name="report_version_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportversion",
            constraint=models.UniqueConstraint(
                fields=("report", "version_number"), name="unique_report_version"
            ),
        ),
    ]
