# Generated by Django 6.0.8 on 2026-08-09 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField()),
                ("is_clinical", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "appointment_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_duration_minutes", models.PositiveSmallIntegerField(default=30)),
                ("break_duration_minutes", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "doctor_availability",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appointment_number",
                    models.CharField(
                        db_index=True, editable=False, max_length=30, unique=True
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial Consultation"),
                            ("FOLLOW_UP", "Follow-up"),
                            ("ROUTINE", "Routine Check-up"),
                            ("EMERGENCY", "Emergency"),
                            ("SPECIALIST", "Specialist Consultation"),
                            ("REVIEW", "Report Review"),
                        ],
                        db_index=True,
                        default="INITIAL",
                        max_length=30,
                    ),
                ),
                (
                    "consultation_mode",
                    models.CharField(
                        choices=[
                            ("IN_PERSON", "In Person"),
                            ("VIDEO", "Video Consultation"),
                            ("AUDIO", "Audio Consultation"),
                        ],
                        default="IN_PERSON",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("scheduled_start", models.DateTimeField(db_index=True)),
                ("scheduled_end", models.DateTimeField(db_index=True)),
                ("reason", models.TextField(blank=True)),
                ("symptoms", models.TextField(blank=True)),
                ("doctor_notes", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "db_table": "appointments",
                "ordering": ["scheduled_start"],
            },
        ),
    ]
