# Generated by Django 6.0.8 on 2026-08-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("core", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="users.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="users.patientprofile",
            ),
        ),
        migrations.AddField(
            model_name="appointmentnote",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointmentnote",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointment_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_slots",
                to="users.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_availability",
                to="core.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "scheduled_start", "status"],
                name="appt_doctor_schedule_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "scheduled_start"], name="appt_patient_schedule_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["organization", "scheduled_start"], name="appt_org_schedule_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "scheduled_start"], name="appt_status_schedule_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentnote",
            index=models.Index(
                fields=["appointment", "created_at"], name="appt_note_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctoravailability",
            index=models.Index(
                fields=["doctor", "weekday", "is_active"],
                name="doctor_weekday_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="doctoravailability",
            constraint=models.UniqueConstraint(
                fields=("doctor", "weekday", "start_time", "end_time"),
                name="unique_doctor_availability",
            ),
        ),
    ]
