# Generated by Django 6.0.8 on 2026-08-09 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT_CREATED", "Appointment Created"),
                            ("APPOINTMENT_CONFIRMED", "Appointment Confirmed"),
                            ("APPOINTMENT_REMINDER", "Appointment Reminder"),
                            ("APPOINTMENT_CANCELLED", "Appointment Cancelled"),
                            ("APPOINTMENT_RESCHEDULED", "Appointment Rescheduled"),
                            ("MEDICAL_REPORT_READY", "Medical Report Ready"),
                            ("IMAGING_REPORT_READY", "Imaging Report Ready"),
                            ("AI_ANALYSIS_COMPLETED", "AI Analysis Completed"),
                            ("AI_REVIEW_REQUIRED", "AI Review Required"),
                            ("PAYMENT_SUCCESS", "Payment Successful"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("SECURITY_ALERT", "Security Alert"),
                            ("SYSTEM", "System Notification"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push Notification"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("action_url", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "scheduled_for",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("provider_name", models.CharField(blank=True, max_length=100)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("response_code", models.CharField(blank=True, max_length=100)),
                ("response_message", models.TextField(blank=True)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notification_delivery_attempts",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("appointment_reminders_enabled", models.BooleanField(default=True)),
                ("marketing_enabled", models.BooleanField(default=False)),
                ("security_alerts_enabled", models.BooleanField(default=True)),
                ("clinical_notifications_enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPOINTMENT_CREATED", "Appointment Created"),
                            ("APPOINTMENT_CONFIRMED", "Appointment Confirmed"),
                            ("APPOINTMENT_REMINDER", "Appointment Reminder"),
                            ("APPOINTMENT_CANCELLED", "Appointment Cancelled"),
                            ("APPOINTMENT_RESCHEDULED", "Appointment Rescheduled"),
                            ("MEDICAL_REPORT_READY", "Medical Report Ready"),
                            ("IMAGING_REPORT_READY", "Imaging Report Ready"),
                            ("AI_ANALYSIS_COMPLETED", "AI Analysis Completed"),
                            ("AI_REVIEW_REQUIRED", "AI Review Required"),
                            ("PAYMENT_SUCCESS", "Payment Successful"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("SECURITY_ALERT", "Security Alert"),
                            ("SYSTEM", "System Notification"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push Notification"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("subject_template", models.CharField(blank=True, max_length=500)),
                ("body_template", models.TextField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "notification_templates",
            },
        ),
    ]
