# Generated by Django 6.0.8 on 2026-08-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationdeliveryattempt",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_attempts",
                to="notifications.notification",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["notification_type", "channel", "is_active"],
                name="notification_template_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationtemplate",
            constraint=models.UniqueConstraint(
                fields=("notification_type", "channel", "name"),
                name="unique_notification_template",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="notifications.notificationtemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdeliveryattempt",
            index=models.Index(
                fields=["notification", "attempted_at"],
                name="notification_attempt_date_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdeliveryattempt",
            constraint=models.UniqueConstraint(
                fields=("notification", "attempt_number"),
                name="unique_notification_attempt",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "status", "created_at"],
                name="notification_user_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["channel", "status", "scheduled_for"],
                name="notification_delivery_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "created_at"],
                name="notification_type_date_idx",
            ),
        ),
    ]
