# Generated by Django 6.0.8 on 2026-08-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationtemplate",
            new_name="notif_template_lookup_idx",
            old_name="notification_template_lookup_idx",
            
        ),
    ]
